# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.item_search_api import ItemSearchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestItemSearchApi(unittest.TestCase):
    """ItemSearchApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.item_search_api.ItemSearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_search(self):
        """Test case for create_search

        Create Saved Search  # noqa: E501
        """
        pass

    def test_list_searches(self):
        """Test case for list_searches

        List Saved Searches  # noqa: E501
        """
        pass

    def test_quick_search(self):
        """Test case for quick_search

        Quick Search  # noqa: E501
        """
        pass

    def test_search_delete(self):
        """Test case for search_delete

        Delete Saved Search  # noqa: E501
        """
        pass

    def test_search_detail(self):
        """Test case for search_detail

        Get Saved Search  # noqa: E501
        """
        pass

    def test_search_results(self):
        """Test case for search_results

        Run Saved Search  # noqa: E501
        """
        pass

    def test_search_update(self):
        """Test case for search_update

        Update Saved Search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
