# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.position_array import PositionArray  # noqa: E501
from swagger_client.rest import ApiException


class TestPositionArray(unittest.TestCase):
    """PositionArray unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPositionArray(self):
        """Test PositionArray"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.position_array.PositionArray()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
