# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.clip_and_ship_api import ClipAndShipApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClipAndShipApi(unittest.TestCase):
    """ClipAndShipApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.clip_and_ship_api.ClipAndShipApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clip_scene(self):
        """Test case for clip_scene

        List Clips  # noqa: E501
        """
        pass

    def test_get_clip(self):
        """Test case for get_clip

        Get Clip  # noqa: E501
        """
        pass

    def test_list_clips(self):
        """Test case for list_clips

        List Clips  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
