# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.string_in_filter import StringInFilter  # noqa: E501
from swagger_client.rest import ApiException


class TestStringInFilter(unittest.TestCase):
    """StringInFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStringInFilter(self):
        """Test StringInFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.string_in_filter.StringInFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
