# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.search_page import SearchPage  # noqa: E501
from swagger_client.rest import ApiException


class TestSearchPage(unittest.TestCase):
    """SearchPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchPage(self):
        """Test SearchPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.search_page.SearchPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
