# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.or_filter import OrFilter  # noqa: E501
from swagger_client.rest import ApiException


class TestOrFilter(unittest.TestCase):
    """OrFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrFilter(self):
        """Test OrFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.or_filter.OrFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
