# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.quad_list_links import QuadListLinks  # noqa: E501
from swagger_client.rest import ApiException


class TestQuadListLinks(unittest.TestCase):
    """QuadListLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuadListLinks(self):
        """Test QuadListLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.quad_list_links.QuadListLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
