# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.clip_request import ClipRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestClipRequest(unittest.TestCase):
    """ClipRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClipRequest(self):
        """Test ClipRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.clip_request.ClipRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
