# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.prev_link import PrevLink  # noqa: E501
from swagger_client.rest import ApiException


class TestPrevLink(unittest.TestCase):
    """PrevLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrevLink(self):
        """Test PrevLink"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.prev_link.PrevLink()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
