# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.next_link import NextLink  # noqa: E501
from swagger_client.rest import ApiException


class TestNextLink(unittest.TestCase):
    """NextLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNextLink(self):
        """Test NextLink"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.next_link.NextLink()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
