# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.date_range_filter import DateRangeFilter  # noqa: E501
from swagger_client.rest import ApiException


class TestDateRangeFilter(unittest.TestCase):
    """DateRangeFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDateRangeFilter(self):
        """Test DateRangeFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.date_range_filter.DateRangeFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
