# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.geo_json_feature_collection import GeoJSONFeatureCollection  # noqa: E501
from swagger_client.rest import ApiException


class TestGeoJSONFeatureCollection(unittest.TestCase):
    """GeoJSONFeatureCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeoJSONFeatureCollection(self):
        """Test GeoJSONFeatureCollection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.geo_json_feature_collection.GeoJSONFeatureCollection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
