# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.not_filter import NotFilter  # noqa: E501
from swagger_client.rest import ApiException


class TestNotFilter(unittest.TestCase):
    """NotFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotFilter(self):
        """Test NotFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.not_filter.NotFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
