# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.item_stats_api import ItemStatsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestItemStatsApi(unittest.TestCase):
    """ItemStatsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.item_stats_api.ItemStatsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_stats(self):
        """Test case for stats

        Search Stats  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
