# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.basemaps_and_mosaics_api import BasemapsAndMosaicsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBasemapsAndMosaicsApi(unittest.TestCase):
    """BasemapsAndMosaicsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.basemaps_and_mosaics_api.BasemapsAndMosaicsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_mosaic(self):
        """Test case for get_mosaic

        Get Mosaic  # noqa: E501
        """
        pass

    def test_get_mosaic_grid(self):
        """Test case for get_mosaic_grid

        Get Mosaic Grid  # noqa: E501
        """
        pass

    def test_get_mosaic_tile_json(self):
        """Test case for get_mosaic_tile_json

        Get Mosaic TileJSON  # noqa: E501
        """
        pass

    def test_get_quad(self):
        """Test case for get_quad

        Get Mosaic Quad  # noqa: E501
        """
        pass

    def test_get_quad_download(self):
        """Test case for get_quad_download

        Get Mosaic Quad URL  # noqa: E501
        """
        pass

    def test_get_quad_download_links(self):
        """Test case for get_quad_download_links

        List Mosaic Quads  # noqa: E501
        """
        pass

    def test_get_quad_items(self):
        """Test case for get_quad_items

        List Mosaic Quad Items  # noqa: E501
        """
        pass

    def test_get_series(self):
        """Test case for get_series

        Get Mosaic Series  # noqa: E501
        """
        pass

    def test_get_series_mosaics(self):
        """Test case for get_series_mosaics

        List Series' Mosaics  # noqa: E501
        """
        pass

    def test_list_mosaics(self):
        """Test case for list_mosaics

        List Mosaics  # noqa: E501
        """
        pass

    def test_list_series(self):
        """Test case for list_series

        List Mosaic Series  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
