# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.asset_type import AssetType  # noqa: F401,E501


class AssetTypePage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'object',
        'asset_types': 'list[AssetType]'
    }

    attribute_map = {
        'links': '_links',
        'asset_types': 'asset_types'
    }

    def __init__(self, links=None, asset_types=None):  # noqa: E501
        """AssetTypePage - a model defined in Swagger"""  # noqa: E501

        self._links = None
        self._asset_types = None
        self.discriminator = None

        if links is not None:
            self.links = links
        if asset_types is not None:
            self.asset_types = asset_types

    @property
    def links(self):
        """Gets the links of this AssetTypePage.  # noqa: E501

        Links to related endpoints.  # noqa: E501

        :return: The links of this AssetTypePage.  # noqa: E501
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this AssetTypePage.

        Links to related endpoints.  # noqa: E501

        :param links: The links of this AssetTypePage.  # noqa: E501
        :type: object
        """

        self._links = links

    @property
    def asset_types(self):
        """Gets the asset_types of this AssetTypePage.  # noqa: E501


        :return: The asset_types of this AssetTypePage.  # noqa: E501
        :rtype: list[AssetType]
        """
        return self._asset_types

    @asset_types.setter
    def asset_types(self, asset_types):
        """Sets the asset_types of this AssetTypePage.


        :param asset_types: The asset_types of this AssetTypePage.  # noqa: E501
        :type: list[AssetType]
        """

        self._asset_types = asset_types

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssetTypePage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
