# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.clip import Clip  # noqa: F401,E501
from swagger_client.models.clip_list_links import ClipListLinks  # noqa: F401,E501


class ClipListPage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'ClipListLinks',
        'clips': 'list[Clip]'
    }

    attribute_map = {
        'links': '_links',
        'clips': 'clips'
    }

    def __init__(self, links=None, clips=None):  # noqa: E501
        """ClipListPage - a model defined in Swagger"""  # noqa: E501

        self._links = None
        self._clips = None
        self.discriminator = None

        if links is not None:
            self.links = links
        if clips is not None:
            self.clips = clips

    @property
    def links(self):
        """Gets the links of this ClipListPage.  # noqa: E501


        :return: The links of this ClipListPage.  # noqa: E501
        :rtype: ClipListLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this ClipListPage.


        :param links: The links of this ClipListPage.  # noqa: E501
        :type: ClipListLinks
        """

        self._links = links

    @property
    def clips(self):
        """Gets the clips of this ClipListPage.  # noqa: E501


        :return: The clips of this ClipListPage.  # noqa: E501
        :rtype: list[Clip]
        """
        return self._clips

    @clips.setter
    def clips(self, clips):
        """Sets the clips of this ClipListPage.


        :param clips: The clips of this ClipListPage.  # noqa: E501
        :type: list[Clip]
        """

        self._clips = clips

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClipListPage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
