# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.filter import Filter  # noqa: F401,E501
from swagger_client.models.geo_json_geometry import GeoJSONGeometry  # noqa: F401,E501


class GeometryFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'config': 'GeoJSONGeometry',
        'field_name': 'str'
    }

    attribute_map = {
        'config': 'config',
        'field_name': 'field_name'
    }

    def __init__(self, config=None, field_name=None):  # noqa: E501
        """GeometryFilter - a model defined in Swagger"""  # noqa: E501

        self._config = None
        self._field_name = None
        self.discriminator = None

        self.config = config
        self.field_name = field_name

    @property
    def config(self):
        """Gets the config of this GeometryFilter.  # noqa: E501


        :return: The config of this GeometryFilter.  # noqa: E501
        :rtype: GeoJSONGeometry
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this GeometryFilter.


        :param config: The config of this GeometryFilter.  # noqa: E501
        :type: GeoJSONGeometry
        """
        if config is None:
            raise ValueError("Invalid value for `config`, must not be `None`")  # noqa: E501

        self._config = config

    @property
    def field_name(self):
        """Gets the field_name of this GeometryFilter.  # noqa: E501


        :return: The field_name of this GeometryFilter.  # noqa: E501
        :rtype: str
        """
        return self._field_name

    @field_name.setter
    def field_name(self, field_name):
        """Sets the field_name of this GeometryFilter.


        :param field_name: The field_name of this GeometryFilter.  # noqa: E501
        :type: str
        """
        if field_name is None:
            raise ValueError("Invalid value for `field_name`, must not be `None`")  # noqa: E501
        allowed_values = ["geometry"]  # noqa: E501
        if field_name not in allowed_values:
            raise ValueError(
                "Invalid value for `field_name` ({0}), must be one of {1}"  # noqa: E501
                .format(field_name, allowed_values)
            )

        self._field_name = field_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GeometryFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
