# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.geo_json_geometry import GeoJSONGeometry  # noqa: F401,E501
from swagger_client.models.item_properties import ItemProperties  # noqa: F401,E501


class Item(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'object',
        'geometry': 'GeoJSONGeometry',
        'id': 'str',
        'properties': 'ItemProperties'
    }

    attribute_map = {
        'links': '_links',
        'geometry': 'geometry',
        'id': 'id',
        'properties': 'properties'
    }

    def __init__(self, links=None, geometry=None, id=None, properties=None):  # noqa: E501
        """Item - a model defined in Swagger"""  # noqa: E501

        self._links = None
        self._geometry = None
        self._id = None
        self._properties = None
        self.discriminator = None

        self.links = links
        if geometry is not None:
            self.geometry = geometry
        self.id = id
        self.properties = properties

    @property
    def links(self):
        """Gets the links of this Item.  # noqa: E501

        Links to related endpoints.  # noqa: E501

        :return: The links of this Item.  # noqa: E501
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this Item.

        Links to related endpoints.  # noqa: E501

        :param links: The links of this Item.  # noqa: E501
        :type: object
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def geometry(self):
        """Gets the geometry of this Item.  # noqa: E501


        :return: The geometry of this Item.  # noqa: E501
        :rtype: GeoJSONGeometry
        """
        return self._geometry

    @geometry.setter
    def geometry(self, geometry):
        """Sets the geometry of this Item.


        :param geometry: The geometry of this Item.  # noqa: E501
        :type: GeoJSONGeometry
        """

        self._geometry = geometry

    @property
    def id(self):
        """Gets the id of this Item.  # noqa: E501

        Item identifier.  # noqa: E501

        :return: The id of this Item.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Item.

        Item identifier.  # noqa: E501

        :param id: The id of this Item.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def properties(self):
        """Gets the properties of this Item.  # noqa: E501


        :return: The properties of this Item.  # noqa: E501
        :rtype: ItemProperties
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this Item.


        :param properties: The properties of this Item.  # noqa: E501
        :type: ItemProperties
        """
        if properties is None:
            raise ValueError("Invalid value for `properties`, must not be `None`")  # noqa: E501

        self._properties = properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Item):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
