# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ItemType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'object',
        'display_description': 'str',
        'display_name': 'str',
        'id': 'str'
    }

    attribute_map = {
        'links': '_links',
        'display_description': 'display_description',
        'display_name': 'display_name',
        'id': 'id'
    }

    def __init__(self, links=None, display_description=None, display_name=None, id=None):  # noqa: E501
        """ItemType - a model defined in Swagger"""  # noqa: E501

        self._links = None
        self._display_description = None
        self._display_name = None
        self._id = None
        self.discriminator = None

        if links is not None:
            self.links = links
        if display_description is not None:
            self.display_description = display_description
        if display_name is not None:
            self.display_name = display_name
        if id is not None:
            self.id = id

    @property
    def links(self):
        """Gets the links of this ItemType.  # noqa: E501

        Links to related endpoints.  # noqa: E501

        :return: The links of this ItemType.  # noqa: E501
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this ItemType.

        Links to related endpoints.  # noqa: E501

        :param links: The links of this ItemType.  # noqa: E501
        :type: object
        """

        self._links = links

    @property
    def display_description(self):
        """Gets the display_description of this ItemType.  # noqa: E501

        Human-readable description of the item type.  # noqa: E501

        :return: The display_description of this ItemType.  # noqa: E501
        :rtype: str
        """
        return self._display_description

    @display_description.setter
    def display_description(self, display_description):
        """Sets the display_description of this ItemType.

        Human-readable description of the item type.  # noqa: E501

        :param display_description: The display_description of this ItemType.  # noqa: E501
        :type: str
        """

        self._display_description = display_description

    @property
    def display_name(self):
        """Gets the display_name of this ItemType.  # noqa: E501

        Human-readable name of the the type.  # noqa: E501

        :return: The display_name of this ItemType.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this ItemType.

        Human-readable name of the the type.  # noqa: E501

        :param display_name: The display_name of this ItemType.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def id(self):
        """Gets the id of this ItemType.  # noqa: E501

        Item type identifier.  # noqa: E501

        :return: The id of this ItemType.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ItemType.

        Item type identifier.  # noqa: E501

        :param id: The id of this ItemType.  # noqa: E501
        :type: str
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItemType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
