# coding: utf-8

"""
    Planet API

    Top level description of the API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.item_type import ItemType  # noqa: F401,E501


class ItemTypePage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'object',
        'item_types': 'list[ItemType]'
    }

    attribute_map = {
        'links': '_links',
        'item_types': 'item_types'
    }

    def __init__(self, links=None, item_types=None):  # noqa: E501
        """ItemTypePage - a model defined in Swagger"""  # noqa: E501

        self._links = None
        self._item_types = None
        self.discriminator = None

        if links is not None:
            self.links = links
        if item_types is not None:
            self.item_types = item_types

    @property
    def links(self):
        """Gets the links of this ItemTypePage.  # noqa: E501

        Links to related endpoints.  # noqa: E501

        :return: The links of this ItemTypePage.  # noqa: E501
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this ItemTypePage.

        Links to related endpoints.  # noqa: E501

        :param links: The links of this ItemTypePage.  # noqa: E501
        :type: object
        """

        self._links = links

    @property
    def item_types(self):
        """Gets the item_types of this ItemTypePage.  # noqa: E501


        :return: The item_types of this ItemTypePage.  # noqa: E501
        :rtype: list[ItemType]
        """
        return self._item_types

    @item_types.setter
    def item_types(self, item_types):
        """Sets the item_types of this ItemTypePage.


        :param item_types: The item_types of this ItemTypePage.  # noqa: E501
        :type: list[ItemType]
        """

        self._item_types = item_types

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItemTypePage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
